from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPOSITORY_ROOT / 'index.html'


@dataclass(frozen=True)
class ProjectRoute:
    slug: str
    title: str
    description: str

    @property
    def path(self) -> str:
        return f'/projects/{self.slug}/'


PROJECT_ROUTES = (
    ProjectRoute(
        slug='alphazero',
        title='AlphaZero-Style Chess & Go Engine — Bertil Braun',
        description='A production-oriented AlphaZero-style chess and Go system with native C++ search, distributed self-play training, rigorous Stockfish evaluation, and a live application.',
    ),
    ProjectRoute(
        slug='llm-light',
        title='LLM-Light — Artifact-Addressed Execution — Bertil Braun',
        description='An experiment executor that resolves complete LLM configurations into reusable stage artifacts, schedules unresolved work across GPUs, and recovers completed stages after relaunch.',
    ),
    ProjectRoute(
        slug='agentic-llm-systems',
        title='Agentic LLM Systems — Bertil Braun',
        description='Three distinct projects spanning durable workflow execution, evidence-gated coding, and an independent A2A/MCP multi-agent story narrator.',
    ),
    ProjectRoute(
        slug='voice-light',
        title='Voice-Light — Low-Latency Voice Agent — Bertil Braun',
        description='An end-to-end streaming voice-agent project covering data generation, labeling, causal turn-taking, evaluation, and a live full-duplex deployment.',
    ),
    ProjectRoute(
        slug='scalable-llm-evaluation',
        title='Scalable Automated LLM Evaluation — Bertil Braun',
        description='GEM² 2025 research on pairwise LLM evaluation and Elo aggregation for open-ended outputs, alongside a domain-agnostic competency-extraction thesis.',
    ),
    ProjectRoute(
        slug='gybelock',
        title='GybeLock — Windsurfing Video Intelligence — Bertil Braun',
        description='A deployed computer-vision system for windsurfing footage with specialist detection and pose models, tracking, stabilization, and interactive rider views.',
    ),
    ProjectRoute(
        slug='traffic-signal-control',
        title='Graph-Based Traffic Signal Control — Bertil Braun',
        description='A graph reinforcement-learning method whose movement-level policy transfers across variable road topologies and signal phase sets.',
    ),
    ProjectRoute(
        slug='aws-light',
        title='AWS-Light — Local Cloud Platform — Bertil Braun',
        description='A readable local cloud-platform simulator with declarative manifests, orchestration, ingress policy, storage, databases, health checks, and autoscaling.',
    ),
)


def replace_once(document: str, pattern: str, replacement: str) -> str:
    updated_document, replacement_count = re.subn(pattern, replacement, document, count=1)
    if replacement_count != 1:
        raise ValueError(f'Expected one metadata match for {pattern!r}, found {replacement_count}')
    return updated_document


def render_route(source: str, route: ProjectRoute) -> str:
    canonical_url = f'https://bertil-braun.de{route.path}'
    document = source.replace(
        '<!doctype html>',
        '<!doctype html>\n<!-- Generated by tools/build_project_routes.py; edit index.html instead. -->',
        1,
    )
    document = replace_once(document, r'<title>.*?</title>', f'<title>{route.title}</title>')
    document = replace_once(
        document,
        r'<meta name="description" content="[^"]*">',
        f'<meta name="description" content="{route.description}">',
    )
    document = replace_once(
        document,
        r'<link rel="canonical" href="[^"]*">',
        f'<link rel="canonical" href="{canonical_url}">',
    )
    for property_name, content in (
        ('og:title', route.title),
        ('og:description', route.description),
        ('og:url', canonical_url),
    ):
        document = replace_once(
            document,
            rf'<meta property="{re.escape(property_name)}" content="[^"]*">',
            f'<meta property="{property_name}" content="{content}">',
        )
    for metadata_name, content in (
        ('twitter:title', route.title),
        ('twitter:description', route.description),
    ):
        document = replace_once(
            document,
            rf'<meta name="{re.escape(metadata_name)}" content="[^"]*">',
            f'<meta name="{metadata_name}" content="{content}">',
        )
    return document


def build_routes() -> None:
    source = SOURCE_PATH.read_text(encoding='utf-8')
    for route in PROJECT_ROUTES:
        output_directory = REPOSITORY_ROOT / 'projects' / route.slug
        output_directory.mkdir(parents=True, exist_ok=True)
        (output_directory / 'index.html').write_text(render_route(source, route), encoding='utf-8', newline='\n')


if __name__ == '__main__':
    build_routes()
