from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPOSITORY_ROOT / 'index.html'


@dataclass(frozen=True)
class PageRoute:
    path: str
    title: str
    description: str


PAGE_ROUTES = (
    PageRoute(
        path='/projects/alphazero/',
        title='AlphaZero-Style Chess & Go Engine — Bertil Braun',
        description='A production-oriented AlphaZero-style chess and Go system with native C++ search, distributed self-play training, rigorous Stockfish evaluation, and a live application.',
    ),
    PageRoute(
        path='/projects/llm-light/',
        title='LLM-Light — Artifact-Addressed Execution — Bertil Braun',
        description='An experiment system that keeps end-to-end LLM configurations self-contained while reusing compatible work, scheduling concurrent GPU stages, and preserving progress across relaunches.',
    ),
    PageRoute(
        path='/projects/agentic-llm-systems/',
        title='Agentic LLM Systems — Bertil Braun',
        description='Three distinct projects spanning durable workflow execution, evidence-gated coding, and an independent A2A/MCP multi-agent story narrator.',
    ),
    PageRoute(
        path='/projects/voice-light/',
        title='Voice-Light — Full-Duplex Streaming Voice Agent — Bertil Braun',
        description='A live full-duplex voice agent spanning conversational training data, model adaptation, causal evaluation, interruption-aware control, and two-GPU streaming deployment, documented in an arXiv paper.',
    ),
    PageRoute(
        path='/projects/scalable-llm-evaluation/',
        title='Scalable Automated Evaluation with LLMs — Bertil Braun',
        description='A reference-free evaluation framework combining bidirectional pairwise LLM judgments with Elo aggregation, validated against rankings from 20 experts and published at GEM² 2025.',
    ),
    PageRoute(
        path='/projects/gybelock/',
        title='GybeLock — Offline Windsurfing Video Tracking — Bertil Braun',
        description='An offline computer-vision system that preserves rider identity through difficult windsurfing footage and produces stable rider-focused videos in a live application.',
    ),
    PageRoute(
        path='/projects/traffic-signal-control/',
        title='Graph-Based Traffic Signal Control — Bertil Braun',
        description='A graph-based reinforcement-learning controller that applies one learned movement-scoring model across road networks with different junction layouts and legal signal phases.',
    ),
    PageRoute(
        path='/projects/aws-light/',
        title='AWS-Light — Local Cloud Platform — Bertil Braun',
        description='A readable local cloud-platform simulator with declarative manifests, orchestration, ingress policy, storage, databases, health checks, and autoscaling.',
    ),
    PageRoute(
        path='/writing/',
        title='Writing — Bertil Braun',
        description='Papers, technical reports, and theses covering machine-learning systems, language-model evaluation, speech, computer vision, graph reinforcement learning, and software verification.',
    ),
)


def replace_once(document: str, pattern: str, replacement: str) -> str:
    updated_document, replacement_count = re.subn(pattern, replacement, document, count=1)
    if replacement_count != 1:
        raise ValueError(f'Expected one metadata match for {pattern!r}, found {replacement_count}')
    return updated_document


def render_route(source: str, route: PageRoute) -> str:
    canonical_url = f'https://bertil-braun.de{route.path}'
    document = source.replace(
        '<!doctype html>',
        '<!doctype html>\n<!-- Generated by tools/build_project_routes.py; edit index.html instead. -->',
        1,
    )
    document = replace_once(document, r'<title>.*?</title>', f'<title>{route.title}</title>')
    document = replace_once(
        document,
        r'<meta name="description" content="[^"]*">',
        f'<meta name="description" content="{route.description}">',
    )
    document = replace_once(
        document,
        r'<link rel="canonical" href="[^"]*">',
        f'<link rel="canonical" href="{canonical_url}">',
    )
    for property_name, content in (
        ('og:title', route.title),
        ('og:description', route.description),
        ('og:url', canonical_url),
    ):
        document = replace_once(
            document,
            rf'<meta property="{re.escape(property_name)}" content="[^"]*">',
            f'<meta property="{property_name}" content="{content}">',
        )
    for metadata_name, content in (
        ('twitter:title', route.title),
        ('twitter:description', route.description),
    ):
        document = replace_once(
            document,
            rf'<meta name="{re.escape(metadata_name)}" content="[^"]*">',
            f'<meta name="{metadata_name}" content="{content}">',
        )
    return document


def build_routes() -> None:
    source = SOURCE_PATH.read_text(encoding='utf-8')
    for route in PAGE_ROUTES:
        output_directory = REPOSITORY_ROOT / route.path.strip('/')
        output_directory.mkdir(parents=True, exist_ok=True)
        (output_directory / 'index.html').write_text(render_route(source, route), encoding='utf-8', newline='\n')


if __name__ == '__main__':
    build_routes()
